build-and-test-buffyboard:
  image: alpine:3.19
  tags:
    - saas-linux-small-amd64
  script:
    - apk -q add git bash build-base meson linux-headers inih-dev libinput-dev eudev-dev
    - git submodule init
    - git submodule update
    - cd buffyboard
    - ./test/test-all.sh

build-and-test-unl0kr-with-drm:
  image: alpine:3.19
  tags:
    - saas-linux-small-amd64
  script:
    - apk -q add git bash build-base meson linux-headers inih-dev libinput-dev libxkbcommon-dev libdrm-dev scdoc
    - git submodule init
    - git submodule update
    - cd unl0kr
    - ./test/test-with-drm.sh

build-and-test-unl0kr-without-drm:
  image: alpine:3.19
  tags:
    - saas-linux-small-amd64
  script:
    - apk -q add git bash build-base meson linux-headers inih-dev libinput-dev libxkbcommon-dev scdoc
    - git submodule init
    - git submodule update
    - cd unl0kr
    - ./test/test-without-drm.sh
